apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: tanzu-java-web-app
    carto.run/workload-namespace: tap-install
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
  - name: testing_pipeline_params
    value:
      job-name: maven_test
      secret-name: jenkins-tls
      job-params: "[{\"name\":\"GIT-URL\",\"value\":\"https://github.com/dsharmaa4/tanzu-java-web-app\"},{\"name\":\"GIT-BRANCH\",\"value\":\"main\"}]"
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      owner: team-vmware-tanzu-se
      system: dev
      description: "A set of API endpoints to manage the resources within the inclusion app."
  source:
    git:
      url: https://github.com/dsharmaa4/tanzu-java-web-app.git
      ref:
        branch: main
