apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
  - name: testing_pipeline_params
    value:
      job-name: maven_test
      secret-name: jenkins-tls
      job-params: "[{\"name\":\"GIT-URL\",\"value\":\"https://github.com/dsharmaa4/tanzu-java-web-app\"},{\"name\":\"GIT-BRANCH\",\"value\":\"main\"}]"
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      owner: team-vmware-tanzu-se
      system: dev
      description: "A set of API endpoints to manage the resources within the inclusion app."
  source:
    git:
      url: https://github.com/dsharmaa4/tanzu-java-web-app.git
      ref:
        branch: main
