apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      owner: team-vmware-tanzu-se
      system: dev
      description: "A set of API endpoints to manage the resources within the inclusion app."
  source:
    git:
      url: https://github.com/dsharmaa4/tanzu-java-web-app.git
      ref:
        branch: main
build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
